// Relative range of pitch motor
#define MAX_PITCH_ANGLE 0.19f
#define MIN_PITCH_ANGLE -0.04f

// Relative range of yaw motor
#define MAX_YAW_ANGLE 0.58f
#define MIN_YAW_ANGLE -0.58f

// Absolute position of yaw motor when gimbal is in flat positio
#define MIN_YAW_MOTOR_POSITION -0.31f
#define FLAT_PITCH_MOTOR_POSITION -0.40f  //-0.6646f -0.64f -> flat

#define PITCH_STUCK_THRESHOLD 2.0f
#define YAW_STUCK_THRESHOLD 2.0f

#define PITCH_STUCK_COUNT 20
#define YAW_STUCK_COUNT 20

#define FRICTION_WHEEL_TARGET_RPM 5700.0f
#define LOADER_TARGET_POSITION_CHANGE 0.697777f
#define LOADER_FREQUENCY 22.0f
#define LOADER_STEP_TIME (1000.0f / LOADER_FREQUENCY)
#define LOADER_STUCK_RPM_THRESHOLD 5.0f

#define LOADER_STUCK_CURRENT_THRESHOLD 6.0f
#define LOADER_STUCK_COUNT_THRESHOLD 200
#define LOADER_RESTORE_TIME_LIMIT 100
#define LOADER_RESTORE_ANGLE_LIMIT 0.03f
#define LOADER_SPEED 168.0f

#define LOADER_STUCK_COOLDOWN 100
#define LOADER_STUCK_BACK_ANGLE (15.0f / 57.3f)
#define LOADER_STUCK_FORWARD 0.0f

#define LOADER_SAFE_RPM 1.0f

#define RC_YAW_SENSITIVITY 0.0000005f
#define RC_PITCH_SENSITIVITY 0.0000001f
#define AUTOAIM_YAW_SENSITIVITY 0.005f
#define AUTOAIM_PITCH_SENSITIVITY 0.005f